apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: virtualization
  namespace: openshift-gitops
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: '{{name}}-virtualization'
    spec:
      project: default
      source:
        repoURL: https://github.com/0xFelix/gitops-demo.git
        targetRevision: HEAD
        path: virtualization/manifests
      destination:
        server: '{{server}}'
        namespace: openshift-cnv
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true
